{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "otf-agent.serviceAccountName" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - "*"
    verbs:
      - "get"
      - "list"
{{- end }}
