name: Release Chart

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: "."

  update-readme:
    runs-on: ubuntu-latest
    needs: release
    container: golang:alpine
    steps:
      - name: Install git
        run: apk add git
      - uses: actions/checkout@v4
      - name: update readme
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          git clone https://github.com/norwoodj/helm-docs.git
          rm -rf helm-docs/cmd/helm-docs/testdata helm-docs/example-charts
          cd helm-docs/cmd/helm-docs
          go build
          cd ../../..
          helm-docs/cmd/helm-docs/helm-docs
          git config --global --add safe.directory "*"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add otf-agent/README.md
          git commit -m "Update README.md"
          git push || true
